import { createClient } from '@supabase/supabase-js';
const fakeData = [
    {
      "Name": "Combs",
      "Vorname": "Dale",
      "Straße": "Concord Street",
      "PLZ": 10405,
      "Ort": "Durham",
      "Festnetz": "(944) 586-3596",
      "Mobiltelefon": "(900) 403-3020",
      "E-Mail": "dalecombs@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Swanson",
      "Vorname": "Haney",
      "Straße": "Pleasant Place",
      "PLZ": 10405,
      "Ort": "Gerber",
      "Festnetz": "(951) 468-3148",
      "Mobiltelefon": "(924) 405-3716",
      "E-Mail": "haneyswanson@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Wise",
      "Vorname": "Mckenzie",
      "Straße": "Keap Street",
      "PLZ": 10405,
      "Ort": "Maplewood",
      "Festnetz": "(801) 547-2015",
      "Mobiltelefon": "(828) 513-2349",
      "E-Mail": "mckenziewise@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Sears",
      "Vorname": "Petty",
      "Straße": "Madison Street",
      "PLZ": 10405,
      "Ort": "Coloma",
      "Festnetz": "(867) 506-2587",
      "Mobiltelefon": "(865) 430-3019",
      "E-Mail": "pettysears@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Jarvis",
      "Vorname": "Simon",
      "Straße": "Remsen Street",
      "PLZ": 10405,
      "Ort": "Snelling",
      "Festnetz": "(900) 501-3327",
      "Mobiltelefon": "(850) 530-3247",
      "E-Mail": "simonjarvis@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Patrick",
      "Vorname": "Albert",
      "Straße": "Banker Street",
      "PLZ": 10405,
      "Ort": "Lupton",
      "Festnetz": "(980) 522-2281",
      "Mobiltelefon": "(818) 508-3847",
      "E-Mail": "albertpatrick@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Ruiz",
      "Vorname": "Knight",
      "Straße": "Aurelia Court",
      "PLZ": 10405,
      "Ort": "Cliff",
      "Festnetz": "(908) 567-2110",
      "Mobiltelefon": "(862) 459-2263",
      "E-Mail": "knightruiz@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Koch",
      "Vorname": "Marks",
      "Straße": "Nautilus Avenue",
      "PLZ": 10405,
      "Ort": "Balm",
      "Festnetz": "(983) 464-2552",
      "Mobiltelefon": "(885) 411-3211",
      "E-Mail": "markskoch@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Mcintyre",
      "Vorname": "Effie",
      "Straße": "Brightwater Court",
      "PLZ": 10405,
      "Ort": "Oceola",
      "Festnetz": "(940) 547-2202",
      "Mobiltelefon": "(975) 539-2862",
      "E-Mail": "effiemcintyre@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Good",
      "Vorname": "Colon",
      "Straße": "Fair Street",
      "PLZ": 10405,
      "Ort": "Caron",
      "Festnetz": "(937) 523-3154",
      "Mobiltelefon": "(855) 499-2829",
      "E-Mail": "colongood@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Henson",
      "Vorname": "Bond",
      "Straße": "Jay Street",
      "PLZ": 10405,
      "Ort": "Remington",
      "Festnetz": "(806) 423-2476",
      "Mobiltelefon": "(888) 452-3271",
      "E-Mail": "bondhenson@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Barry",
      "Vorname": "Victoria",
      "Straße": "Hausman Street",
      "PLZ": 10405,
      "Ort": "Dupuyer",
      "Festnetz": "(968) 437-2001",
      "Mobiltelefon": "(936) 466-2450",
      "E-Mail": "victoriabarry@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Farmer",
      "Vorname": "Shaffer",
      "Straße": "Bradford Street",
      "PLZ": 10405,
      "Ort": "Cleary",
      "Festnetz": "(980) 502-3108",
      "Mobiltelefon": "(947) 542-3931",
      "E-Mail": "shafferfarmer@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Reeves",
      "Vorname": "Allen",
      "Straße": "Tampa Court",
      "PLZ": 10405,
      "Ort": "Hessville",
      "Festnetz": "(953) 504-3650",
      "Mobiltelefon": "(928) 486-2779",
      "E-Mail": "allenreeves@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Bush",
      "Vorname": "Hewitt",
      "Straße": "Kings Place",
      "PLZ": 10405,
      "Ort": "Columbus",
      "Festnetz": "(836) 480-3781",
      "Mobiltelefon": "(844) 464-3084",
      "E-Mail": "hewittbush@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Brown",
      "Vorname": "Esther",
      "Straße": "Hubbard Street",
      "PLZ": 10405,
      "Ort": "Statenville",
      "Festnetz": "(837) 530-3083",
      "Mobiltelefon": "(909) 448-3172",
      "E-Mail": "estherbrown@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Sheppard",
      "Vorname": "Melanie",
      "Straße": "Farragut Place",
      "PLZ": 10405,
      "Ort": "Lafferty",
      "Festnetz": "(864) 413-3145",
      "Mobiltelefon": "(873) 506-3152",
      "E-Mail": "melaniesheppard@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Ramsey",
      "Vorname": "Bennett",
      "Straße": "Micieli Place",
      "PLZ": 10405,
      "Ort": "Aberdeen",
      "Festnetz": "(951) 511-3414",
      "Mobiltelefon": "(892) 454-3512",
      "E-Mail": "bennettramsey@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Oliver",
      "Vorname": "Georgia",
      "Straße": "Lafayette Walk",
      "PLZ": 10405,
      "Ort": "Winston",
      "Festnetz": "(891) 423-3634",
      "Mobiltelefon": "(894) 599-3162",
      "E-Mail": "georgiaoliver@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Mays",
      "Vorname": "Pearl",
      "Straße": "Willmohr Street",
      "PLZ": 10405,
      "Ort": "Mapletown",
      "Festnetz": "(868) 550-2883",
      "Mobiltelefon": "(883) 464-3893",
      "E-Mail": "pearlmays@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Woodward",
      "Vorname": "Trevino",
      "Straße": "Montgomery Place",
      "PLZ": 10405,
      "Ort": "Joppa",
      "Festnetz": "(998) 446-2792",
      "Mobiltelefon": "(821) 423-3042",
      "E-Mail": "trevinowoodward@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Walsh",
      "Vorname": "Eliza",
      "Straße": "Canarsie Road",
      "PLZ": 10405,
      "Ort": "Ruckersville",
      "Festnetz": "(998) 588-2475",
      "Mobiltelefon": "(878) 416-2205",
      "E-Mail": "elizawalsh@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Vargas",
      "Vorname": "Williams",
      "Straße": "Dahill Road",
      "PLZ": 10405,
      "Ort": "Waterford",
      "Festnetz": "(895) 501-2689",
      "Mobiltelefon": "(868) 456-3418",
      "E-Mail": "williamsvargas@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Bailey",
      "Vorname": "Holcomb",
      "Straße": "Milton Street",
      "PLZ": 10405,
      "Ort": "Alden",
      "Festnetz": "(802) 568-2966",
      "Mobiltelefon": "(918) 419-3092",
      "E-Mail": "holcombbailey@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Francis",
      "Vorname": "Melissa",
      "Straße": "Burnett Street",
      "PLZ": 10405,
      "Ort": "Day",
      "Festnetz": "(880) 478-2163",
      "Mobiltelefon": "(943) 510-3259",
      "E-Mail": "melissafrancis@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Luna",
      "Vorname": "Marian",
      "Straße": "Troutman Street",
      "PLZ": 10405,
      "Ort": "Zeba",
      "Festnetz": "(924) 522-2848",
      "Mobiltelefon": "(908) 430-2833",
      "E-Mail": "marianluna@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Nguyen",
      "Vorname": "Lorie",
      "Straße": "Irvington Place",
      "PLZ": 10405,
      "Ort": "Thatcher",
      "Festnetz": "(959) 463-2445",
      "Mobiltelefon": "(981) 543-3711",
      "E-Mail": "lorienguyen@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Hudson",
      "Vorname": "Anthony",
      "Straße": "Jewel Street",
      "PLZ": 10405,
      "Ort": "Morriston",
      "Festnetz": "(898) 472-3262",
      "Mobiltelefon": "(932) 597-2716",
      "E-Mail": "anthonyhudson@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Estrada",
      "Vorname": "Lesa",
      "Straße": "Sullivan Street",
      "PLZ": 10405,
      "Ort": "Hardyville",
      "Festnetz": "(920) 429-3473",
      "Mobiltelefon": "(872) 467-2345",
      "E-Mail": "lesaestrada@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Hicks",
      "Vorname": "Patrica",
      "Straße": "Arlington Avenue",
      "PLZ": 10405,
      "Ort": "Walton",
      "Festnetz": "(865) 533-2641",
      "Mobiltelefon": "(849) 419-3877",
      "E-Mail": "patricahicks@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Huber",
      "Vorname": "Mandy",
      "Straße": "Himrod Street",
      "PLZ": 10405,
      "Ort": "Topanga",
      "Festnetz": "(938) 578-2218",
      "Mobiltelefon": "(942) 580-3420",
      "E-Mail": "mandyhuber@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Kirkland",
      "Vorname": "Dawn",
      "Straße": "Sackett Street",
      "PLZ": 10405,
      "Ort": "Accoville",
      "Festnetz": "(885) 461-2805",
      "Mobiltelefon": "(980) 589-3898",
      "E-Mail": "dawnkirkland@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Phillips",
      "Vorname": "Payne",
      "Straße": "Highland Boulevard",
      "PLZ": 10405,
      "Ort": "Bannock",
      "Festnetz": "(894) 599-2943",
      "Mobiltelefon": "(894) 597-2059",
      "E-Mail": "paynephillips@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Barlow",
      "Vorname": "Lorraine",
      "Straße": "President Street",
      "PLZ": 10405,
      "Ort": "Deercroft",
      "Festnetz": "(998) 463-2147",
      "Mobiltelefon": "(951) 446-2912",
      "E-Mail": "lorrainebarlow@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "West",
      "Vorname": "Deidre",
      "Straße": "Noll Street",
      "PLZ": 10405,
      "Ort": "Cochranville",
      "Festnetz": "(852) 445-3166",
      "Mobiltelefon": "(884) 511-3733",
      "E-Mail": "deidrewest@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Coffey",
      "Vorname": "Kaye",
      "Straße": "Ashland Place",
      "PLZ": 10405,
      "Ort": "Hinsdale",
      "Festnetz": "(902) 546-2660",
      "Mobiltelefon": "(901) 524-3388",
      "E-Mail": "kayecoffey@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Mcintosh",
      "Vorname": "Jackie",
      "Straße": "Nevins Street",
      "PLZ": 10405,
      "Ort": "Hatteras",
      "Festnetz": "(927) 523-2279",
      "Mobiltelefon": "(921) 575-2707",
      "E-Mail": "jackiemcintosh@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Dickson",
      "Vorname": "Bernadette",
      "Straße": "Wyona Street",
      "PLZ": 10405,
      "Ort": "Elwood",
      "Festnetz": "(964) 483-2447",
      "Mobiltelefon": "(965) 589-2082",
      "E-Mail": "bernadettedickson@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Tate",
      "Vorname": "Hanson",
      "Straße": "Beard Street",
      "PLZ": 10405,
      "Ort": "Sehili",
      "Festnetz": "(904) 409-3938",
      "Mobiltelefon": "(983) 504-2435",
      "E-Mail": "hansontate@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Golden",
      "Vorname": "Nola",
      "Straße": "Williamsburg Street",
      "PLZ": 10405,
      "Ort": "Independence",
      "Festnetz": "(896) 545-3457",
      "Mobiltelefon": "(871) 454-3649",
      "E-Mail": "nolagolden@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Gardner",
      "Vorname": "Rollins",
      "Straße": "Harrison Avenue",
      "PLZ": 10405,
      "Ort": "Croom",
      "Festnetz": "(924) 468-3933",
      "Mobiltelefon": "(881) 411-2335",
      "E-Mail": "rollinsgardner@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Harper",
      "Vorname": "Aurora",
      "Straße": "Kingsway Place",
      "PLZ": 10405,
      "Ort": "Rehrersburg",
      "Festnetz": "(930) 437-3003",
      "Mobiltelefon": "(839) 538-2303",
      "E-Mail": "auroraharper@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Fuentes",
      "Vorname": "Wood",
      "Straße": "Grove Street",
      "PLZ": 10405,
      "Ort": "Walker",
      "Festnetz": "(838) 570-2968",
      "Mobiltelefon": "(803) 513-2492",
      "E-Mail": "woodfuentes@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Horton",
      "Vorname": "Mcintosh",
      "Straße": "Kenmore Court",
      "PLZ": 10405,
      "Ort": "Newkirk",
      "Festnetz": "(830) 455-2734",
      "Mobiltelefon": "(950) 589-3507",
      "E-Mail": "mcintoshhorton@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Kinney",
      "Vorname": "Noreen",
      "Straße": "Huron Street",
      "PLZ": 10405,
      "Ort": "Kanauga",
      "Festnetz": "(832) 431-3044",
      "Mobiltelefon": "(822) 557-3374",
      "E-Mail": "noreenkinney@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Petty",
      "Vorname": "Guerra",
      "Straße": "Oriental Boulevard",
      "PLZ": 10405,
      "Ort": "Dale",
      "Festnetz": "(977) 525-3553",
      "Mobiltelefon": "(905) 533-3684",
      "E-Mail": "guerrapetty@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Bennett",
      "Vorname": "Vonda",
      "Straße": "Ash Street",
      "PLZ": 10405,
      "Ort": "Roberts",
      "Festnetz": "(808) 444-3576",
      "Mobiltelefon": "(828) 580-2580",
      "E-Mail": "vondabennett@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Sanford",
      "Vorname": "Kirsten",
      "Straße": "Brown Street",
      "PLZ": 10405,
      "Ort": "Herbster",
      "Festnetz": "(908) 401-2270",
      "Mobiltelefon": "(838) 459-2191",
      "E-Mail": "kirstensanford@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Carpenter",
      "Vorname": "Guy",
      "Straße": "Brevoort Place",
      "PLZ": 10405,
      "Ort": "Oley",
      "Festnetz": "(966) 459-2279",
      "Mobiltelefon": "(878) 452-3887",
      "E-Mail": "guycarpenter@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Holcomb",
      "Vorname": "Fletcher",
      "Straße": "Eckford Street",
      "PLZ": 10405,
      "Ort": "Chical",
      "Festnetz": "(946) 502-3354",
      "Mobiltelefon": "(867) 491-3233",
      "E-Mail": "fletcherholcomb@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    },
    {
      "Name": "Booker",
      "Vorname": "Norton",
      "Straße": "Granite Street",
      "PLZ": 10405,
      "Ort": "Cumminsville",
      "Festnetz": "(860) 458-2303",
      "Mobiltelefon": "(805) 524-2644",
      "E-Mail": "nortonbooker@konnect.com",
      "Gewuenschte_Weiterbildung": "Fachinformatiker",
      "Gewuenschter_Starttermin": null,
      "Umfang": null,
      "Zustellung_Angebot": "Mail",
      "Beratungstermin": null,
      "Bemerkungen": null,
      "Creator": null,
      "Einwilligung": true
    }
  ]

const supabase = createClient(
    'https://lqgnahenxkmdkenuxbxw.supabase.co',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZ25haGVueGttZGtlbnV4Ynh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTUyMDg0NDksImV4cCI6MjAxMDc4NDQ0OX0.XrMlC1LGwKXDw0yg1AqKjzsiUdV-XLsfLEfdSq7gJh0',
);

let { "data": _data, "error": errorLogin } = await supabase.auth.signInWithPassword({
    email: "",
    password: "",
});
if (errorLogin != null) console.log(errorLogin);



const { data, error } = await supabase.from('Kontakte').insert(fakeData);
console.log(data);
console.log(error);






